import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

file_path = r"C:\Users\becke\Downloads\useful databases\secondTestRegionSort.csv"
df = pd.read_csv(file_path)

dftest = df.loc[:,'year ':].astype(float)

imputer = KNNImputer(n_neighbors=2, weights='uniform')
df_imputed = imputer.fit_transform(dftest)
pd_imp = pd.DataFrame(df_imputed, columns=dftest.columns.values)


figb, axb = plt.subplots(4, 4, figsize=(10, 10))

axb[0,0].hist(pd_imp.loc[:, 'unemployment %'], bins=50, color='blue', edgecolor='black', label='unemployment')
axb[0,1].hist(pd_imp.loc[:, 'population % 16-64'], bins=50, color='blue', edgecolor='black', label='population 16-64')
axb[0,2].hist(pd_imp.loc[:, 'population-density (persons per km^2)'], bins=50, color='blue', edgecolor='black', label='population-density')
axb[0,3].hist(pd_imp.loc[:, 'GDP per head £'], bins=50, color='blue', edgecolor='black', label='GDP per head')
axb[0,3].set_xticks([0, 40000, 80000])
axb[1,0].hist(pd_imp.loc[:, 'GDP per head current value £'], bins=50, color='blue', edgecolor='black', label='GDP per head (current value)')
axb[1,1].hist(pd_imp.loc[:, 'further education/skills participation per 100000'], bins=50, color='blue', edgecolor='black', label='further education/skills participation')
axb[1,2].hist(pd_imp.loc[:, 'net additions to housing stock per 1000 dwellings '], bins=50, color='blue', edgecolor='black', label='net additions to housing stock')
axb[1,3].hist(pd_imp.loc[:, 'children in relative poverty %'], bins=50, color='blue', edgecolor='black', label='children in relative poverty')
axb[2,0].hist(pd_imp.loc[:, '% of people achieving maths and english gcses by 19 '], bins=50, color='blue', edgecolor='black', label='% of people achieving maths and english gcses by 19')
axb[2,1].hist(pd_imp.loc[:, '% of people with level 3 qualifications'], bins=50, color='blue', edgecolor='black', label='% of people with level 3 qualifications')
axb[2,2].hist(pd_imp.loc[:, '% children with expected reading writing and maths level at ks2'], bins=50, color='blue', edgecolor='black', label='% children with expected reading writing and maths level at ks2')
axb[2,3].hist(pd_imp.loc[:, '% with no qualifications'], bins=50, color='blue', edgecolor='black', label='% with no qualifications')
axb[3,0].hist(pd_imp.loc[:, '% of obesity in adults '], bins=50, color='blue', edgecolor='black', label='% of obesity in adults ')
axb[3,1].hist(pd_imp.loc[:, 'apprenticeship achievements per 100000'], bins=50, color='blue', edgecolor='black', label='apprenticeship achievements per 100000')
axb[3,2].hist(pd_imp.loc[:, '% children with persistent absence from schools '], bins=50, color='white', edgecolor='red', label='% children with persistent absence from schools ')
axb[3,3].hist(pd_imp.loc[:, '% of people smoking  '], bins=50, color='blue', edgecolor='black', label='% of people smoking')
plt.tight_layout(pad=2)
plt.show()

figc, axc = plt.subplots(4, 4, figsize=(10, 10))

axc[0,0].hist(pd_imp.loc[:, 'preventable cardiovascular deaths per 100000'], bins=50, color='blue', edgecolor='black')
axc[0,1].hist(pd_imp.loc[:, '% of cancer diagnoses in stage 1 or 2'], bins=50, color='blue', edgecolor='black')
axc[0,2].hist(pd_imp.loc[:, 'years in good health (male)'], bins=50, color='blue', edgecolor='black')
axc[0,3].hist(pd_imp.loc[:, 'years in good health (female)'], bins=50, color='blue', edgecolor='black')
axc[1,0].hist(pd_imp.loc[:, 'Average Anxiety out of 10'], bins=50, color='blue', edgecolor='black')
axc[1,1].hist(pd_imp.loc[:, 'Average feeling life is worthwhile out of 10'], bins=50, color='blue', edgecolor='black')
axc[1,2].hist(pd_imp.loc[:, 'Average happiness out of 10'], bins=50, color='blue', edgecolor='black')
axc[1,3].hist(pd_imp.loc[:, 'Average life satisfaction'], bins=50, color='blue', edgecolor='black')
axc[2,0].hist(pd_imp.loc[:, 'time to employment centre by walking/public transport'], bins=50, color='blue', edgecolor='black')
axc[2,1].hist(pd_imp.loc[:, 'sports facilities per 10000'], bins=50, color='blue', edgecolor='black')
axc[2,2].hist(pd_imp.loc[:, 'Museums per 100000'], bins=50, color='blue', edgecolor='black')
axc[2,3].hist(pd_imp.loc[:, '% of people within 30 minute walk of train station'], bins=50, color='white', edgecolor='red')
axc[3,0].hist(pd_imp.loc[:, '% of people within 30 minute walk to library'], bins=50, color='blue', edgecolor='black')
axc[3,1].hist(pd_imp.loc[:, '% of people engaged in the arts '], bins=50, color='blue', edgecolor='black')
axc[3,2].hist(pd_imp.loc[:, '% of people who visited a heritage site '], bins=50, color='blue', edgecolor='black')
axc[3,3].hist(pd_imp.loc[:, '% people who visited a library '], bins=50, color='blue', edgecolor='black')
plt.tight_layout(pad=2)
plt.show()

figd, axd = plt.subplots(3, 4, figsize=(10, 10))

axd[0,0].hist(pd_imp.loc[:, 'average number of parks and playing fields within 1000m'], bins=50, color='blue', edgecolor='black')
axd[0,1].hist(pd_imp.loc[:, 'greenhouse gas emmisions tCO2e'], bins=50, color='blue', edgecolor='black')
axd[0,2].hist(pd_imp.loc[:, 'average combined size of parks playing fields and public gardens'], bins=50, color='blue', edgecolor='black')
axd[0,3].hist(pd_imp.loc[:, 'total crimes '], bins=50, color='blue', edgecolor='black')
axd[0,3].set_xticks([0,75000,150000])
axd[1,0].hist(pd_imp.loc[:, 'crimes against people'], bins=50, color='blue', edgecolor='black')
axd[1,0].set_xticks([0, 30000, 60000])
axd[1,1].hist(pd_imp.loc[:, '% religious'], bins=50, color='blue', edgecolor='black')
axd[1,2].hist(pd_imp.loc[:, '% no religion'], bins=50, color='blue', edgecolor='black')
axd[1,3].hist(pd_imp.loc[:, 'yearly_spending(million £ 2025/26 rates unweighted)'], bins=50, color='blue', edgecolor='black')
axd[2,0].hist(pd_imp.loc[:, 'available_seats'], bins=50, color='white', edgecolor='red')

plt.tight_layout(pad=2)
plt.show()
'''
fig, ax = plt.subplots(2, 2, figsize=(8, 6), constrained_layout=True)

ax[0,0].hist(pd_imp.loc[:, 'unemployment %'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("unemployment %")
ax[0,0].set_xlabel("%")
ax[0,1].hist(pd_imp.loc[:, 'population % 16-64'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("population % 16-64")
ax[0,1].set_xlabel('%')
ax[1,0].hist(pd_imp.loc[:, 'population-density (persons per km^2)'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("population-density (persons/km^2)")
ax[1,0].set_xlabel("persons per km^2")
ax[1,1].hist(pd_imp.loc[:, 'GDP per head £'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("GDP per head £")
ax[1,1].set_xlabel("£")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("£")
ax[0,1].set_xlabel("persons per 100000")
ax[1,0].set_xlabel("additions per 1000")
ax[1,1].set_xlabel("%")

ax[0,0].hist(pd_imp.loc[:, 'GDP per head current value £'], bins=50, color='blue', edgecolor='black')
#ax[0,0].xlabel("GDP current value £")
ax[0,0].set_title("GDP per head current value £")
ax[0,1].hist(pd_imp.loc[:, 'further education/skills participation per 100000'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("further education/skills participation /100000")
ax[1,0].hist(pd_imp.loc[:, 'net additions to housing stock per 1000 dwellings '], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("additions to housing stock/1000 dwellings")
ax[1,1].hist(pd_imp.loc[:, 'children in relative poverty %'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("children in relative poverty %")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("%")
ax[0,1].set_xlabel("%")
ax[1,0].set_xlabel("%")
ax[1,1].set_xlabel("%")

ax[0,0].hist(pd_imp.loc[:, '% of people achieving maths and english gcses by 19 '], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("% achieving maths and english gcses by 19")
ax[0,1].hist(pd_imp.loc[:, '% of people with level 3 qualifications'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("% people with level 3 qualifications")
ax[1,0].hist(pd_imp.loc[:, '% children with expected reading writing and maths level at ks2'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("% at expected reading, writing and maths level ks2")
ax[1,1].hist(pd_imp.loc[:, '% with no qualifications'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("% with no qualifications")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("%")
ax[0,1].set_xlabel("achievements per 100000")
ax[1,0].set_xlabel("%")
ax[1,1].set_xlabel("%")

ax[0,0].hist(pd_imp.loc[:, '% of obesity in adults '], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("% of obesity in adults ")
ax[0,1].hist(pd_imp.loc[:, 'apprenticeship achievements per 100000'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("apprenticeship achievements per 100,000")
ax[1,0].hist(pd_imp.loc[:, '% children with persistent absence from schools '], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("% children with persistent absence from schools ")
ax[1,1].hist(pd_imp.loc[:, '% of people smoking  '], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title('% of people smoking ')

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("deaths per 100000")
ax[0,1].set_xlabel("%")
ax[1,0].set_xlabel("years")
ax[1,1].set_xlabel("years")

ax[0,0].hist(pd_imp.loc[:, 'preventable cardiovascular deaths per 100000'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("preventable cardiovascular deaths per 100000")
ax[0,1].hist(pd_imp.loc[:, '% of cancer diagnoses in stage 1 or 2'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("% of cancer diagnoses in stage 1 or 2")
ax[1,0].hist(pd_imp.loc[:, 'years in good health (male)'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("years in good health (male)")
ax[1,1].hist(pd_imp.loc[:, 'years in good health (female)'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("years in good health (female)")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("1-10")
ax[0,1].set_xlabel("1-10")
ax[1,0].set_xlabel("1-10")
ax[1,1].set_xlabel("1-10")

ax[0,0].hist(pd_imp.loc[:, 'Average Anxiety out of 10'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("Average Anxiety out of 10")
ax[0,1].hist(pd_imp.loc[:, 'Average feeling life is worthwhile out of 10'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("Average feeling life is worthwhile out of 10")
ax[1,0].hist(pd_imp.loc[:, 'Average happiness out of 10'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("Average happiness out of 10")
ax[1,1].hist(pd_imp.loc[:, 'Average life satisfaction'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("Average life satisfaction")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(10, 8),constrained_layout=True)
ax[0,0].set_xlabel("minutes")
ax[0,1].set_xlabel("facilities per 10000")
ax[1,0].set_xlabel("museums per 100000")
ax[1,1].set_xlabel("%")

ax[0,0].hist(pd_imp.loc[:, 'time to employment centre by walking/public transport'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("time to employment centre by walking/public transport")
ax[0,1].hist(pd_imp.loc[:, 'sports facilities per 10000'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("sports facilities per 10000")
ax[1,0].hist(pd_imp.loc[:, 'Museums per 100000'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("Museums per 100000")
ax[1,1].hist(pd_imp.loc[:, '% of people within 30 minute walk of train station'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("% of people within 30 minute walk of train station")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("%")
ax[0,1].set_xlabel("%")
ax[1,0].set_xlabel("%")
ax[1,1].set_xlabel("%")

ax[0,0].hist(pd_imp.loc[:, '% of people within 30 minute walk to library'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("% of people within 30 minute walk to library")
ax[0,1].hist(pd_imp.loc[:, '% of people engaged in the arts '], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("% of people engaged in the arts ")
ax[1,0].hist(pd_imp.loc[:, '% of people who visited a heritage site '], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("% of people who visited a heritage site ")
ax[1,1].hist(pd_imp.loc[:, '% people who visited a library '], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("% people who visited a library ")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("count")
ax[0,1].set_xlabel("tCO2e")
ax[1,0].set_xlabel("1e6")
ax[1,1].set_xlabel("count")

ax[0,0].hist(pd_imp.loc[:, 'average number of parks and playing fields within 1000m'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("average number of parks/fields in 1000m")
ax[0,1].hist(pd_imp.loc[:, 'greenhouse gas emmisions tCO2e'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("greenhouse gas emmisions tCO2e")
ax[1,0].hist(pd_imp.loc[:, 'average combined size of parks playing fields and public gardens'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("average combined size of public green space")
ax[1,1].hist(pd_imp.loc[:, 'total crimes '], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("total crimes")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("count")
ax[0,1].set_xlabel("%")
ax[1,0].set_xlabel("%")
ax[1,1].set_xlabel("")

ax[0,0].hist(pd_imp.loc[:, 'crimes against people'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("crimes against people")
ax[0,1].hist(pd_imp.loc[:, '% religious'], bins=50, color='red', edgecolor='black')
ax[0,1].set_title("% people who are religious ")
ax[1,0].hist(pd_imp.loc[:, '% no religion'], bins=50, color='green', edgecolor='black')
ax[1,0].set_title("% people not religious")

plt.show()

fig, ax = plt.subplots(2, 2, figsize=(8, 6),constrained_layout=True)
ax[0,0].set_xlabel("million £ 2025/26 rates unweighted")
ax[0,1].set_xlabel("")
ax[1,0].set_xlabel("")
ax[1,1].set_xlabel("count")

ax[0,0].hist(pd_imp.loc[:, 'yearly_spending(million £ 2025/26 rates unweighted)'], bins=50, color='blue', edgecolor='black')
ax[0,0].set_title("yearly_spending")
ax[1,1].hist(pd_imp.loc[:, 'available_seats'], bins=50, color='yellow', edgecolor='black')
ax[1,1].set_title("available_seats")

plt.show()
'''